import json
from math import exp, sin
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

from src.quadrature import (
    CompositeGaussLegendre2,
    Integral,
    Interval,
    estimate_by_step_doubling,
    integrate,
)

# https://www.integral-calculator.com/#expr=sin%28x%29%2Fx&lbound=0&ubound=5&numonly=1
SINE_INTEGRAL_REFERENCE = 1.5499312449446741

def sinc(x):
    if x == 0.0:
        return 1.0

    return sin(x) / x


def quadrature_experiments():
    integral = Integral(sinc, Interval(0.0, 5.0)) # integral_0^5 sin(x)/x
    rows = []
    previous = None
    for N in [1, 2, 4, 8, 16, 32, 64, 128, 256]:
        value = integrate(integral, CompositeGaussLegendre2(N)) # Perform the approximation using N => Q_N
        estimate = None if previous is None else abs(value - previous) / 15.0 # (Q_2N - Q_N )/15
        rows.append(
            {
                "N": N, # Number of subintervals
                "evaluations": 2 * N, # Number of function evaluations
                "value": value, # Q_n, i.e., the approximation
                "absolute_error": abs(value - SINE_INTEGRAL_REFERENCE), # Error using the real solution
                "relative_error": abs(value - SINE_INTEGRAL_REFERENCE) / abs(SINE_INTEGRAL_REFERENCE),
                "step_doubling_estimate": estimate, # Step doubling estimation, doesn't need the real solution
            }
        )
        previous = value

    result = estimate_by_step_doubling(integral, rtol=1e-10) # Double N and stop when the tolerance is reached
    return {
        "reference": SINE_INTEGRAL_REFERENCE, # Real value
        "rows": rows,
        "selected": {
            "N": result.N,
            "evaluations_in_final_rule": result.evaluations,
            "evaluations_in_search": result.total_evaluations,
            "value": result.value,
            "richardson_value": result.richardson_value,
            "error_estimate": result.error_estimate,
            "actual_absolute_error": abs(result.value - SINE_INTEGRAL_REFERENCE),
            "actual_relative_error": abs(result.value - SINE_INTEGRAL_REFERENCE) / abs(SINE_INTEGRAL_REFERENCE),
        },
    }

# This plotting function was generated by an LLM and hand checked by me
def draw_quadrature_figure(results, image_directory):
    # Plots the convergence graph
    rows = results["rows"]
    evaluations = np.array([row["evaluations"] for row in rows[1:]])
    errors = np.array([row["absolute_error"] for row in rows[1:]])
    estimates = np.array([row["step_doubling_estimate"] for row in rows[1:]])

    figure, axis = plt.subplots(figsize=(6.0, 3.8), constrained_layout=True)
    axis.loglog(evaluations, errors, "o-", color="#2e77bb", label="Actual error")
    axis.loglog(
        evaluations,
        estimates,
        "s--",
        color="#e09f3e",
        label="Step double estimate",
    )
    axis.axhline(1e-10, color="#d1495b", linestyle=":", linewidth=1.1)
    axis.set(xlabel="Number of function values", ylabel="Absolute error")
    axis.grid(alpha=0.25, which="both")
    axis.legend(frameon=False)
    figure.savefig(image_directory / "hw2_quadrature.svg", bbox_inches="tight")
    plt.close(figure)


if __name__ == "__main__":
    image_directory = Path("img")
    result_directory = Path("results")
    image_directory.mkdir(exist_ok=True)
    result_directory.mkdir(exist_ok=True)

    quadrature_results = quadrature_experiments() # Perform the integration experiments on sinc
    results = {"quadrature": quadrature_results}

    draw_quadrature_figure(quadrature_results, image_directory)
    output_path = result_directory / "hw2_part2.json"
    output_path.write_text(json.dumps(results, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(results, indent=2))