import json
from math import pi
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

from src.mpendulum import (
    DOPRI5,
    PendulumParameters,
    harmonic_angle,
    harmonic_period,
    pendulum_energy,
    pendulum_period,
    solve_pendulum,
)

# General method and parameters
PARAMETERS = PendulumParameters(gravity=9.81, length=1.0, mass=1.0)
METHOD = DOPRI5(
    rtol=2e-12,
    atol=2e-14,
    initial_step=harmonic_period(PARAMETERS) / 100.0,
    max_step=harmonic_period(PARAMETERS) / 20.0,
)


def comparison_experiment():
    """Compare the mathematical and harmonic pendulums"""

    # Point grid for the harmonic pendulum on three periods
    linear_period = harmonic_period(PARAMETERS)
    end_time = 3.0 * linear_period
    grid = np.linspace(0.0, end_time, 1_501)

    # Three amplitudes to test from
    amplitudes = [0.1, 1.0, 2.5]
    results = []
    solutions = {}
    for amplitude in amplitudes:
        solution = solve_pendulum(
            amplitude,
            0.0,
            end_time,
            parameters=PARAMETERS,
            method=METHOD,
        )
        nonlinear = solution(grid)[:, 0]  # The nonlinear (mathematical) pendulum solution using DOPRI5
        harmonic = harmonic_angle(grid, amplitude, parameters=PARAMETERS)  # (exact) Harmonic solution
        solutions[amplitude] = solution
        results.append(
            {
                "theta0": amplitude,
                "normalized_energy":
                    pendulum_energy(amplitude, 0.0, PARAMETERS)
                    / (PARAMETERS.mass * PARAMETERS.gravity * PARAMETERS.length),
                "max_angle_difference": float(np.max(np.abs(nonlinear - harmonic))),  # Difference between the models
                "accepted_steps": solution.accepted_steps,
                "rejected_steps": solution.rejected_steps,
            }
        )
    return results, solutions


def period_experiment():
    """Produces the data for the period - energy graph of the nonlinear pendulum

        Solve the nonlinear pendulum
        find its numerical period
        calculate its initial energy
        stores the pair
    """
    plot_amplitudes = np.linspace(0.05, 0.95 * pi, 31)  # Evenly spaced amplitudes
    table_amplitudes = np.array([0.1, 0.5, 1.0, 1.5, 2.0, 2.5, 2.9])  # Report table
    amplitudes = np.unique(np.concatenate((plot_amplitudes, table_amplitudes)))

    rows = []
    linear_period = harmonic_period(PARAMETERS)

    # Test with multiple amplitudes
    for amplitude in amplitudes:
        result = pendulum_period(float(amplitude), parameters=PARAMETERS, method=METHOD)
        energy = pendulum_energy(float(amplitude), 0.0, PARAMETERS)
        rows.append(
            {
                "theta0": float(amplitude),
                "energy": energy,
                "normalized_energy": energy / (PARAMETERS.mass * PARAMETERS.gravity * PARAMETERS.length),
                "period": result.period,
                "period_over_harmonic": result.period / linear_period,
                "first_crossing": result.crossings[0].time,
                "second_crossing": result.crossings[1].time,
                "accepted_steps": result.solution.accepted_steps,
                "rejected_steps": result.solution.rejected_steps,
                "selected_for_table": bool(np.any(np.isclose(amplitude, table_amplitudes, atol=0.0))),
            }
        )
    return rows


# This was generated by an LLM, and checked by me
def draw_comparison_figure(solutions: dict[float, object], image_directory: Path) -> None:
    # Create the fixed plotting grid
    linear_period = harmonic_period(PARAMETERS)
    grid = np.linspace(0.0, 3.0 * linear_period, 1_501)
    figure, axes = plt.subplots(3, 1, figsize=(8.0, 7.0), sharex=True)

    for axis, amplitude in zip(axes, [0.1, 1.0, 2.5]):
        # Use Hermite interpolation
        solution = solutions[amplitude]
        axis.plot(
            grid,
            solution(grid)[:, 0],  # Uses hermite here, only plot theta
            color="#2e77bb",
            linewidth=1.7,
            label="matematično nihalo",
        )
        # Plot the harmonic result
        axis.plot(
            grid,
            harmonic_angle(grid, amplitude, parameters=PARAMETERS),
            color="#d1495b",
            linewidth=1.3,
            linestyle="--",
            label="harmonično nihalo",
        )
        axis.set_ylabel(r"$\theta(t)$")
        axis.set_title(rf"$\theta_0={amplitude:g}$, $\omega_0=0$")
        axis.grid(alpha=0.25)
    axes[-1].set_xlabel("time t [s]")
    handles, labels = axes[0].get_legend_handles_labels()
    figure.legend(handles, labels, loc="outside lower center", ncol=2, frameon=False)
    figure.tight_layout(rect=(0.0, 0.055, 1.0, 1.0))
    figure.savefig(image_directory / "hw3_pendulum_comparison.svg", bbox_inches="tight")
    plt.close(figure)


# This was generated by an LLM, and checked by me
def draw_period_figure(rows: list[dict[str, float]], image_directory: Path) -> None:
    # Plot (E_i, T_i)
    # Each item in row represents one pendulum simulation
    energies = np.array([row["normalized_energy"] for row in rows])
    periods = np.array([row["period"] for row in rows])
    linear_period = harmonic_period(PARAMETERS)

    figure, axis = plt.subplots(figsize=(7.2, 4.2), constrained_layout=True)
    # Plot the non linear results
    axis.plot(
        energies,
        periods,
        "o-",
        color="#2e77bb",
        markersize=3.8,
        linewidth=1.5,
        label="Mathematical pendulum (DOPRI5)",
    )
    # Plot the linear results for comparison
    axis.axhline(
        linear_period,
        color="#d1495b",
        linestyle="--",
        linewidth=1.3,
        label="Harmonic pendulum",
    )
    axis.set(
        xlabel=r"Normalized energy $E/(mgl)$",
        ylabel="period T [s]",
    )
    axis.grid(alpha=0.25)
    axis.legend(frameon=False)
    figure.savefig(image_directory / "hw3_period_energy.svg", bbox_inches="tight")
    plt.close(figure)


if __name__ == "__main__":
    image_directory = Path("img")
    result_directory = Path("results")
    image_directory.mkdir(exist_ok=True)
    result_directory.mkdir(exist_ok=True)

    comparison, solutions = comparison_experiment()  # Compare the harmonic and mathematical pendulum
    periods = period_experiment()  # Relationship between period and energy
    results = {
        "parameters": {
            "gravity": PARAMETERS.gravity,
            "length": PARAMETERS.length,
            "mass": PARAMETERS.mass,
            "harmonic_period": harmonic_period(PARAMETERS),
        },
        "method": {
            "rtol": METHOD.rtol,
            "atol": METHOD.atol,
            "initial_step": METHOD.initial_step,
            "max_step": METHOD.max_step,
        },
        "comparison": comparison,
        "period_energy": periods,
    }

    draw_comparison_figure(solutions, image_directory)
    draw_period_figure(periods, image_directory)
    output_path = result_directory / "hw3_pendulum.json"
    output_path.write_text(json.dumps(results, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(results, indent=2))
